# Pre-commit configuration
default_language_version:
    python: python3  # Prefer python3 by default

repos:
- repo: local
  hooks:
    - id: pytest-non-integration
      name: Run non-integration tests
      entry: python3 -m pytest -v -m "not integration" --no-header --capture=no || python -m pytest -v -m "not integration" --no-header --capture=no
      language: python
      types: [python]
      pass_filenames: false
      verbose: true
      additional_dependencies: [pytest, python-dotenv]

    - id: style-check
      name: Style checking
      entry: python3 scripts/lint.py || python scripts/lint.py
      language: python
      types: [python]
      pass_filenames: false
      verbose: true
      additional_dependencies: [ruff]

    - id: security-check
      name: Security checking
      entry: python3 scripts/security.py || python scripts/security.py
      language: python
      types: [python]
      pass_filenames: false
      verbose: true
      additional_dependencies: [bandit, safety]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: detect-private-key
